Repository shuvadeepmondal/HacKerZGuiDe, pull requests merged in 2025-08, with the labels that each got.

#85 Updated the templates and the some templates are added
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/others.md
  .github/workflows/issueOpen.yml
  .github/workflows/selfAssign.yml
Labels: set-up

#87 ✅Fix: Chatbot UI & Response Handling with Full Scroll Support.
  CSS/ai.css
  JS/ai.js
  ai.html
  index.html
Labels: help wanted, level2, gssoc25

#91 Fixed UI Misalignment on Quiz Page
  CSS/quizq.css
  CSS/resources.css
Labels: level2, gssoc25, HackerZGuide

#90 Fix Duplicate Navigation Sidebar and Improve UI Alignment on Homepage #89
  CSS/style.css
  about.html
  contact.html
  faq.html
  index.html
  pp.html
  quiz.html
  quizq.html
  resources.html
  result.html
Labels: level1, gssoc25

#97 Changed style of Cards
  CSS/style.css
  index.html
Labels: level2, gssoc25, HackerZGuide

#108 Contact form submits with invalid data
  JS/contact.js
  contact.html
Labels: level1, gssoc25

#114 Fix navabr for visible of navitems
  CSS/contact.css
  CSS/style.css
  about.html
  index.html
  resources.html
Labels: level1, gssoc25

#115 fix wrapping of Resources card
  CSS/resources.css
Labels: level2, gssoc25

#132 Added dsa sheet for every site in practice section
  resources.html
  sheet1.html
  sheet2.html
  sheet3.html
  sheet4.html
Labels: level3, gssoc25, HackerZGuide

#136 Made navbar same in all pages
  CSS/about.css
  CSS/contact.css
  CSS/faq.css
  CSS/quiz.css
  CSS/resources.css
Labels: level2, gssoc25

#138 ✨ Added Preview button feature for resource cards
  CSS/resources.css
  JS/resources.js
  package-lock.json
  resources.html
Labels: level2, gssoc25

#143 Style change of Contact Us
  CSS/contact.css
  contact.html
Labels: enhancement, level2, gssoc25

#146 Sending PR again
  CSS/contact.css
  contact.html
Labels: level2, gssoc25
